### ISSUE TITLE
Running example.py gives no result

### ISSUE THREAD

**Issue by harshithdwivedi** [ipazc/mtcnn#66] opened 2019-11-26 18:14 UTC
Hi, I'm trying to use `mtcnn` and upon running `example.py`, the only output I get is  : 

```
Using TensorFlow backend.
```
after this, the execution stops without any further error messages.

I'm running this script on Windows 10 with keras 2.0.0.

**Comment by ipazc** [comment] 2019-11-27 08:11
I could not reproduce this issue. 
What version of tensorflow do you have installed?

**Comment by harshithdwivedi** [comment] 2019-11-27 10:53
I'm using TensorFlow version 1.15.0

**Comment by ipazc** [comment] 2024-10-08 16:18
This issue should be fixed in the release version 1.0.0 #133.

**Closed by ipazc** 2024-10-08 16:18 UTC
